package Rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.05.14 18:37:10 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testAseta164 */
  @Test
  public void testAseta164() {    // Pelaaja: 164
    Pelaaja pelaaja = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 166", null, pelaaja.aseta(1,"Sasu Toivonen")); 
    assertEquals("From: Pelaaja line: 167", null, pelaaja.aseta(2,"Sasuke")); 
    assertEquals("From: Pelaaja line: 169", null, pelaaja.aseta(9,"1940")); 
    assertEquals("From: Pelaaja line: 168", "Saa olla vain numeroita.", pelaaja.aseta(3,"kissa")); 
    assertEquals("From: Pelaaja line: 169", null, pelaaja.aseta(3,"19")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString246 */
  @Test
  public void testToString246() {    // Pelaaja: 246
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("   3  |  Toivonen Sasu   "); 
    assertEquals("From: Pelaaja line: 249", true, pelaaja.toString().startsWith("3|Toivonen Sasu|"));  // on enemmäkin kuin 2 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse271 */
  @Test
  public void testParse271() {    // Pelaaja: 271
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("   3  |  Toivonen Sasu   "); 
    assertEquals("From: Pelaaja line: 274", 3, pelaaja.getTunnusNro()); 
    assertEquals("From: Pelaaja line: 275", true, pelaaja.toString().startsWith("3|Toivonen Sasu|")); 
    pelaaja.rekisteroi(); 
    int n = pelaaja.getTunnusNro(); 
    pelaaja.parse(""+(n+20)); 
    pelaaja.rekisteroi(); 
    assertEquals("From: Pelaaja line: 281", n+20+1, pelaaja.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi312 */
  @Test
  public void testRekisteroi312() {    // Pelaaja: 312
    Pelaaja tommi = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 314", 0, tommi.getTunnusNro()); 
    tommi.rekisteroi(); 
    Pelaaja kaisa = new Pelaaja(); 
    kaisa.rekisteroi(); 
    int t = tommi.getTunnusNro(); 
    int k = kaisa.getTunnusNro(); 
    assertEquals("From: Pelaaja line: 320", k-1, t);
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi357 */
  @Test
  public void testGetNimi357() {    // Pelaaja: 357
    Pelaaja sasu = new Pelaaja(); 
    sasu.taytaTiedoillaSasuToivonen(); 
    { String _l_=sasu.getNimi(),_r_="Sasu Toivonen .*"; if ( !_l_.matches(_r_) ) fail("From: Pelaaja line: 360" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone435 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone435() throws CloneNotSupportedException {    // Pelaaja: 435
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("   3  |  Toivonen Sasu   | 123"); 
    Pelaaja kopio = pelaaja.clone(); 
    assertEquals("From: Pelaaja line: 440", pelaaja.toString(), kopio.toString()); 
    pelaaja.parse("   4  |  Toivonen Saku   | 123"); 
    assertEquals("From: Pelaaja line: 442", false, kopio.toString().equals(pelaaja.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals458 */
  @Test
  public void testEquals458() {    // Pelaaja: 458
    Pelaaja pelaaja1 = new Pelaaja(); 
    pelaaja1.parse("   7  |  Toivonen Saku   | sakkerz"); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.parse("   7  |  Toivonen Saku   | sakkerz"); 
    Pelaaja pelaaja3 = new Pelaaja(); 
    pelaaja3.parse("   7  |  Toivonen Saku   | saccerz"); 
    assertEquals("From: Pelaaja line: 466", true, pelaaja1.equals(pelaaja2)); 
    assertEquals("From: Pelaaja line: 467", true, pelaaja2.equals(pelaaja1)); 
    assertEquals("From: Pelaaja line: 468", false, pelaaja1.equals(pelaaja3)); 
    assertEquals("From: Pelaaja line: 469", false, pelaaja3.equals(pelaaja2)); 
  } // Generated by ComTest END
}