package Rekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.05.14 18:31:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PeliTest {



  // Generated by ComTest BEGIN
  /** 
   * testClone70 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone70() throws CloneNotSupportedException {    // Peli: 70
    Peli peli = new Peli(); 
    peli.parse("   2   |  10  |   Borderlands 2  | PS4  "); 
    Peli kopio = peli.clone(); 
    assertEquals("From: Peli line: 75", peli.toString(), kopio.toString()); 
    peli.parse("   1   |  11  |   Destiny  | PC  "); 
    assertEquals("From: Peli line: 77", false, kopio.toString().equals(peli.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna142 */
  @Test
  public void testAnna142() {    // Peli: 142
    Peli peli = new Peli(); 
    peli.parse("   2   |  10  |   Minecraft  | PC  "); 
    assertEquals("From: Peli line: 145", "2", peli.anna(0)); 
    assertEquals("From: Peli line: 146", "10", peli.anna(1)); 
    assertEquals("From: Peli line: 147", "Minecraft", peli.anna(2)); 
    assertEquals("From: Peli line: 148", "PC", peli.anna(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse181 */
  @Test
  public void testParse181() {    // Peli: 181
    Peli peli = new Peli(); 
    peli.parse("   2   |  10  |   Minecraft  | PC  "); 
    assertEquals("From: Peli line: 184", 10, peli.getJasenNro()); 
    assertEquals("From: Peli line: 185", "2|10|Minecraft|PC", peli.toString()); 
    peli.rekisteroi(); 
    int n = peli.getTunnusNro(); 
    peli.parse(""+(n+20)); 
    peli.rekisteroi(); 
    assertEquals("From: Peli line: 191", n+20+1, peli.getTunnusNro()); 
    assertEquals("From: Peli line: 192", "" + (n+20+1) + "|10||", peli.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString206 */
  @Test
  public void testToString206() {    // Peli: 206
    Peli peli = new Peli(); 
    peli.parse("   2   |  10  |   Borderlands 2  | PS4  "); 
    assertEquals("From: Peli line: 209", "2|10|Borderlands 2|PS4", peli.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi277 */
  @Test
  public void testRekisteroi277() {    // Peli: 277
    Peli freddy1 = new Peli(); 
    assertEquals("From: Peli line: 279", 0, freddy1.getTunnusNro()); 
    freddy1.rekisteroi(); 
    Peli freddy2 = new Peli(); 
    freddy2.rekisteroi(); 
    int n1 = freddy1.getTunnusNro(); 
    int n2 = freddy2.getTunnusNro(); 
    assertEquals("From: Peli line: 285", n2-1, n1); 
  } // Generated by ComTest END
}